---
abstract: 'Perl class for polynomials in one variable'
author:
  - 'Martin Becker <becker-cpan-mp@cozap.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Basename: 0
  File::Spec: 0
  FindBin: 0
  Math::Complex: 0
  Test: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Polynomial
no_index:
  directory:
    - t
    - inc
recommends:
  Math::BigRat: 0
  Math::Complex: 0
  Math::ModInt: 0
requires:
  Carp: 0
  overload: 0
  perl: 5.006
version: 1.006
