--- #YAML:1.0
name:                Math-Polynomial
version:             0.04
abstract:            Perl class for working with polynomials.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Martin Becker <becker-cpan-mp@cozap.com>
